// Code generated by entc, DO NOT EDIT.

package runtime

import (
	"github.com/genevieve/ent-tests/ent/friendrequest"
	"github.com/genevieve/ent-tests/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	friendrequestHooks := schema.FriendRequest{}.Hooks()
	friendrequest.Hooks[0] = friendrequestHooks[0]
}

const (
	Version = "v0.9.2-0.20220113113942-3a426390de5a"            // Version of ent codegen.
	Sum     = "h1:h2Ga08iM/NOvBGWLFxnbqiJDoC4icPF/TRAfC6lEl48=" // Sum of ent codegen.
)
