// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/genevieve/ent-tests/ent/friendrequest"
	"github.com/genevieve/ent-tests/ent/user"
)

// FriendRequestCreate is the builder for creating a FriendRequest entity.
type FriendRequestCreate struct {
	config
	mutation *FriendRequestMutation
	hooks    []Hook
}

// SetSourceID sets the "source_id" field.
func (frc *FriendRequestCreate) SetSourceID(i int) *FriendRequestCreate {
	frc.mutation.SetSourceID(i)
	return frc
}

// SetDestinationID sets the "destination_id" field.
func (frc *FriendRequestCreate) SetDestinationID(i int) *FriendRequestCreate {
	frc.mutation.SetDestinationID(i)
	return frc
}

// SetStatus sets the "status" field.
func (frc *FriendRequestCreate) SetStatus(f friendrequest.Status) *FriendRequestCreate {
	frc.mutation.SetStatus(f)
	return frc
}

// SetSource sets the "source" edge to the User entity.
func (frc *FriendRequestCreate) SetSource(u *User) *FriendRequestCreate {
	return frc.SetSourceID(u.ID)
}

// SetDestination sets the "destination" edge to the User entity.
func (frc *FriendRequestCreate) SetDestination(u *User) *FriendRequestCreate {
	return frc.SetDestinationID(u.ID)
}

// Mutation returns the FriendRequestMutation object of the builder.
func (frc *FriendRequestCreate) Mutation() *FriendRequestMutation {
	return frc.mutation
}

// Save creates the FriendRequest in the database.
func (frc *FriendRequestCreate) Save(ctx context.Context) (*FriendRequest, error) {
	var (
		err  error
		node *FriendRequest
	)
	if len(frc.hooks) == 0 {
		if err = frc.check(); err != nil {
			return nil, err
		}
		node, err = frc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FriendRequestMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = frc.check(); err != nil {
				return nil, err
			}
			frc.mutation = mutation
			if node, err = frc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(frc.hooks) - 1; i >= 0; i-- {
			if frc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = frc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, frc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (frc *FriendRequestCreate) SaveX(ctx context.Context) *FriendRequest {
	v, err := frc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (frc *FriendRequestCreate) Exec(ctx context.Context) error {
	_, err := frc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (frc *FriendRequestCreate) ExecX(ctx context.Context) {
	if err := frc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (frc *FriendRequestCreate) check() error {
	if _, ok := frc.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "FriendRequest.source_id"`)}
	}
	if _, ok := frc.mutation.DestinationID(); !ok {
		return &ValidationError{Name: "destination_id", err: errors.New(`ent: missing required field "FriendRequest.destination_id"`)}
	}
	if _, ok := frc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "FriendRequest.status"`)}
	}
	if v, ok := frc.mutation.Status(); ok {
		if err := friendrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FriendRequest.status": %w`, err)}
		}
	}
	if _, ok := frc.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required edge "FriendRequest.source"`)}
	}
	if _, ok := frc.mutation.DestinationID(); !ok {
		return &ValidationError{Name: "destination", err: errors.New(`ent: missing required edge "FriendRequest.destination"`)}
	}
	return nil
}

func (frc *FriendRequestCreate) sqlSave(ctx context.Context) (*FriendRequest, error) {
	_node, _spec := frc.createSpec()
	if err := sqlgraph.CreateNode(ctx, frc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (frc *FriendRequestCreate) createSpec() (*FriendRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &FriendRequest{config: frc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: friendrequest.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: friendrequest.FieldID,
			},
		}
	)
	if value, ok := frc.mutation.Status(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: friendrequest.FieldStatus,
		})
		_node.Status = value
	}
	if nodes := frc.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friendrequest.SourceTable,
			Columns: []string{friendrequest.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SourceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := frc.mutation.DestinationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friendrequest.DestinationTable,
			Columns: []string{friendrequest.DestinationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DestinationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FriendRequestCreateBulk is the builder for creating many FriendRequest entities in bulk.
type FriendRequestCreateBulk struct {
	config
	builders []*FriendRequestCreate
}

// Save creates the FriendRequest entities in the database.
func (frcb *FriendRequestCreateBulk) Save(ctx context.Context) ([]*FriendRequest, error) {
	specs := make([]*sqlgraph.CreateSpec, len(frcb.builders))
	nodes := make([]*FriendRequest, len(frcb.builders))
	mutators := make([]Mutator, len(frcb.builders))
	for i := range frcb.builders {
		func(i int, root context.Context) {
			builder := frcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FriendRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, frcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, frcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, frcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (frcb *FriendRequestCreateBulk) SaveX(ctx context.Context) []*FriendRequest {
	v, err := frcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (frcb *FriendRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := frcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (frcb *FriendRequestCreateBulk) ExecX(ctx context.Context) {
	if err := frcb.Exec(ctx); err != nil {
		panic(err)
	}
}
